### ISSUE TITLE
Charlotte CATS GTFS data

### ISSUE THREAD

**Issue by rmglennon** [transitland/gtfs-archives-not-hosted-elsewhere#22]
We need to add this feed that came in by FOIA (through an email from Matt at TransitScreen). This is Charlotte CATS, which is one that we don't currently have. Looks like we'd need to download the files, zip them, and put them in this repo. 

https://www.muckrock.com/foi/charlotte-161/cats-schedules-routes-and-stops-in-machine-readable-format-35067/

@stevevance - would you mind helping on this one?

**Comment by stevevance** [comment]
The file is here: https://github.com/transitland/gtfs-archives-not-hosted-elsewhere/blob/master/charlotte-cats.zip

[Dispatcher feed](https://transit.land/dispatcher/feeds/f-dnq-charlotteareatransitsystem)
[Feed registry](https://transit.land/feed-registry/operators/o-dnq-charlotteareatransitsystem)
