### ISSUE TITLE
Remove Utah Transit Authority

### ISSUE THREAD

**Issue by stevevance** [transitland/gtfs-archives-not-hosted-elsewhere#4]
The Utah Transit Authority has an official feed now ([check the Feed Registry](https://transit.land/feed-registry/operators/o-9x0-utahtransitauthority)), and I've enqueued it to be imported at level 2. 

Once that's been successfully imported, then the UTA's feed should be removed from this repo.

**Comment by drewda** [comment]
@stevevance 👍  Glad to hear that this repo is serving its purpose as a short-term bridge.

**Comment by drewda** [comment]
Looks like the feed has been re-imported from its new location: https://transit.land/dispatcher/feeds/f-9x0-uta
