### ISSUE TITLE
Witchita stop_times.txt Empty

### ISSUE THREAD

**Issue by RideSchedules** [transitland/gtfs-archives-not-hosted-elsewhere#47]
Hello,

The Wicthita stop_times.txt is empty.

**Comment by drewda** [comment]
Following up with Wichita contact: https://interline-io.freshdesk.com/a/tickets/27

**Comment by drewda** [comment]
from City of Wichita:
> Wichita Transit published a new schedule last week but we have since discovered a couple of problems with that schedule.  As soon as the scheduler has a chance to do a minor publish I hope to be able to send you updated files.

In the meantime, we will revert to the prior feed version.
