### ISSUE TITLE
Memphis Area Transit Authority

### ISSUE THREAD

**Issue by kylebarron** [transitland/gtfs-archives-not-hosted-elsewhere#58]
https://www.muckrock.com/foi/memphis-319/mata-schedules-routes-and-stops-in-machine-readable-format-44566/

**Comment by drewda** [comment]
@kylebarron thanks for noticing this GTFS feed. Do you know if any more recent versions are available?

**Comment by kylebarron** [comment]
I don't know. That was all I could find from searching.

**Comment by drewda** [comment]
MATA now has a public GTFS feed available.

Adding to Transitland on https://github.com/transitland/transitland-atlas/pull/153
